title: venaCode
author: venaCode
email: venacode93@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome. This page is the beginning for the beginning.

# social links
twitter_username: Sorry, Not yet # DO NOT include the @ character, or else the build will fail!
github_username: venaCode  # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
